[marvell-arm64]: Add kernel patches and kconfig changes
sonic-net/sonic-linux-kernel pull request #307
Opened 2023-02-13 08:52 UTC by pavannaregundi

These patches add necessary support for marvell platforms - 98DX35xx and 98CX85xx.

Testing:
Build of target/sonic-marvell-arm64.bin, load of the image on AC5XRD(98DX35xx ) and Falcon(98CX85xx) switches, verified that all dockers operational and “show interface status” displays all ports correctly.

Build of target/sonic-marvell-armhf.bin, load of the image on M0, verified that all dockers operational and “show interface status” displays all ports correctly.

2023-02-13 11:25 UTC, paulmenzel commented
Please write more [elaborate commit messages](https://cbea.ms/git-commit/) (for your commit and the added patches). SONiC requires the added patches to be sent upstream, so they do not need to be maintained by the SONiC community longterm.

2023-02-13 11:28 UTC, pavannaregundi commented
@paulmenzel Sub commits do have description. Please check them.

2023-02-13 11:34 UTC, paulmenzel commented
Yes, they are much better than before. But they do not follow common patterns (statements (with a verb in imperative mood), no dot/period at the end of commit message summaries). Also, the Gerrit change-Ids are not needed, unless you tell us the public Gerrit instance. The missing commit message more referred to the added patch files.

On what device did you test this?

2023-02-14 07:47 UTC, pavannaregundi commented
@paulmenzel I have corrected some commit messages. Some part of the patches are upstreamed, those details are mentioned along with commit message. 
Testing details are mentioned above.

2023-02-15 16:56 UTC, radha-danda commented
@paulmenzel, can you please review the PR? All your comments are addressed by @pavannaregundi

2023-02-16 21:16 UTC, carl-nokia commented
@paulmenzel,  we are struggling a bit to establish a new arm64 pipeline for Microsoft Azure CI/CD and this PR with arm64 support in addition to armhf is the initial foundation for several other PR's to establish the new arm64 pipeline in addition to the existing armhf pipeline.   -- your attention is greatly appreciated; are there any issues we could assist with?

2023-02-17 16:46 UTC, paulmenzel commented
Sorry, the commit messages (of the commits in the merge/pull request) still do not follow the common standard. Additionally, the added patch files also are not properly created with `git format-patch`. Please look at the merge/pull requests from Nvidia how to do it.

2023-02-17 16:56 UTC, carl-nokia commented
Thanks Paul -- we will set up a team review of this PR and address your comments by Monday.

2023-02-21 05:18 UTC, pavannaregundi commented
> Sorry, the commit messages (of the commits in the merge/pull request) still do not follow the common standard. Additionally, the added patch files also are not properly created with `git format-patch`. Please look at the merge/pull requests from Nvidia how to do it.

@paulmenzel I have pushed changes for 'git format-patch' and also addressed commit message to follow common standards. Please see if they are fine now and review the PR.

2023-02-22 04:31 UTC, pavannaregundi commented
@Pavan-Nokia  please review PR

2023-02-24 01:03 UTC, carl-nokia commented
@paulmenzel -- we have both companies meeting tomorrow to review anything needed for this PR  again at 9:30AM EST -- any chance you could join?     Thanks

2023-02-24 06:35 UTC, paulmenzel requested changes
I looked at it ten minutes and already found several cases, that should be improved. No idea, why you do not see it when doing your team meetings.

It’s also not clear, what patches were sent upstream for review (the maintainers are able to “judge” the correctness better than the SONiC kernel folks), and what patches are included already upstream.

For me, I am doing this in my free time, so this was the last comment on this merge/pull request. Especially as I had a bad experience with a Nokia contribution in the past, where promises were made and broken. The other project members should comment and review from now on.

2023-02-24 06:35 UTC, paulmenzel commented on patch/0003-mvneta-setup-xbar-windows-for-ac5.patch
> +Subject: mvneta: setup xbar windows for ac5
The verb is spelled with a space: Set up …

2023-02-24 06:35 UTC, paulmenzel commented on patch/0003-mvneta-setup-xbar-windows-for-ac5.patch
> ++	 * Setup window #0 base 0x0 to target XBAR port 2 (AMB2), attribute 0xb,
Ditto.

2023-02-24 06:35 UTC, paulmenzel commented on patch/0003-mvneta-setup-xbar-windows-for-ac5.patch
> +
Commit message body is missing.

2023-02-24 06:35 UTC, paulmenzel commented on patch/0004-support-be-for-ac5-spi-driver.patch
> +Subject: support be for ac5 spi driver
What is “be”?

2023-02-24 06:35 UTC, paulmenzel commented on patch/0006-mv6xxx-i2c-bus-lock-arb-loss.patch
> +Subject: mv6xxx: i2c bus lock (arb-loss)
No statement.

2023-02-24 06:35 UTC, paulmenzel commented on patch/0006-mv6xxx-i2c-bus-lock-arb-loss.patch
> +Some i2c slaves, mainly SFPs, might cause the bus to
Please reflow for 75 characters per line.

2023-02-24 06:35 UTC, paulmenzel commented on patch/0001-dts-support-for-7020-comexpress.patch
> ++							"mpp59", "mpp60", "mpp61", "mpp62";
Indentation looks incorrect.

2023-02-24 06:35 UTC, paulmenzel commented on patch/0001-dts-support-for-7020-comexpress.patch
> +Subject: dts support for 7020 comexpress
No statement.

2023-02-24 06:35 UTC, paulmenzel commented on patch/0001-dts-support-for-7020-comexpress.patch
> +
Missing commit message body.

2023-02-28 15:00 UTC, carl-nokia commented
@paulmenzel Thanks for your help Paul.  Review focus on this Marvell generated PR had been on technical and operational aspects ensuring a new arm64 target could be built and run without any impact on existing armhf capabilities.  Marvell is working on addressing your feedback for correction. Thank You

2023-03-01 03:55 UTC, pavannaregundi commented
Thanks @paulmenzel for review comments. We will raise a new PR after addressing review comments.

2023-03-01 03:55 UTC, closed without merging