Add arm64 dts and xmc spi device for Wistron platform support
sonic-net/sonic-linux-kernel pull request #433
Opened 2024-09-13 02:10 UTC by twowen

Add kernel configuration, xmc spi device and arm64 dts to SONiC linux kernel for usage on Wistron platform.

2024-09-13 06:06 UTC, paulmenzel requested changes
Thank you for the patches. It’d be great if you amended the sonic-linux-kernel commit message, and also went into the state of upstreaming these patches. The second patch should be fairly easy to do.

The reason is, that not upstreaming these patches is putting the work on moving to newer Linux kernel series on the SONiC maintainers. And they are understaffed.

2024-09-13 06:06 UTC, paulmenzel commented on patch/0001-arm64-dts-marvell-Add-Wistron-ES1227-54TS-board.patch
> +
Please add a commit message body, so that the patch could be upstreamed, and a Signed-off-by line.

2024-09-13 06:06 UTC, paulmenzel commented on patch/0001-arm64-dts-marvell-Add-Wistron-ES1227-54TS-board.patch
> +From: Cody_Chen <cody_chen@wistron.com>
Cody Chen

2024-09-13 06:06 UTC, paulmenzel commented on patch/0001-arm64-dts-marvell-Add-Wistron-ES1227-54TS-board.patch
> +Subject: [PATCH 1/2] Add Wistron dts
Please follow the upstream Linux kernel style.

2024-09-13 06:06 UTC, paulmenzel commented on patch/0001-arm64-dts-marvell-Add-Wistron-ES1227-54TS-board.patch
> ++                                                 <0x1 0x10 0xFDFF 0x200>;
Indentation looks off.

2024-09-13 06:06 UTC, paulmenzel commented on patch/0002-Add-support-for-xmc-spi-device.patch
> +From: Cody_Chen <cody_chen@wistron.com>
Ditto.

2024-09-13 06:06 UTC, paulmenzel commented on patch/0002-Add-support-for-xmc-spi-device.patch
> +Subject: [PATCH 2/2] Add xmc spi device
Please follow the Linux kernel style of how to write the summary.

2024-09-24 10:10 UTC, twowen commented
Thank you @paulmenzel, I'll take a look, thanks again.

2024-10-16 05:50 UTC, twowen commented on patch/kconfig-force-inclusions
> +[marvell]
Thank you @saiarcot895 
The duplicated kernel configurations have been removed from kconfig-force-inclusions.

2024-10-23 02:51 UTC, saiarcot895 approved these changes

2024-10-23 21:01 UTC, saiarcot895 approved these changes

2024-10-23 21:02 UTC, merged