Fix for Winbond flash devices that could not parse SFDP
sonic-net/sonic-linux-kernel pull request #436
Opened 2024-09-30 15:28 UTC by vivekrnv

the following errors are seen on one of our system with w25q128 flash

```
sonic kernel: [    5.814911] spi-nor spi0.0: BFPT parsing failed. Please consider using SPI_NOR_SKIP_SFDP when declaring the flash
sonic kernel: [    5.934937] spi-nor: probe of spi0.0 failed with error -524
```

In 5.10, i see the following:
```
[    4.851862] intel-spi intel-spi: w25q128 (16384 Kbytes)
[    4.928908] Creating 1 MTD partitions on "intel-spi":
```

This is reported elsewhere: https://lore.kernel.org/all/194d6f02-bd70-489d-b883-d7677b6f87b3@gmail.com/T/ and the fix for this is merged in upstream https://github.com/gregkh/linux/commit/d35df77707bf5ae1221b5ba1c8a88cf4fcdd4901 but the backport is not present in the stable versions. 

Until that is backported, the offending commit is reverted

2024-09-30 15:50 UTC, dgsudharsan approved these changes

2024-09-30 20:04 UTC, paulmenzel requested changes
> the following errors are seen on one of our system with w25q128 flash

Which one?

Why not add the patch from the Linux master branch instead of reverting the commit?

2024-09-30 20:30 UTC, vivekrnv commented
msn2100 platform. upstream code is refactored and patch cannot be applied directly. https://github.com/gregkh/linux/commit/d35df77707bf5ae1221b5ba1c8a88cf4fcdd4901.

It seems safe to revert the offending commit than to make an effort to port the upstream change into the stable branch. 

I'll ofcourse change this once the upstream commit is backported to 6.1 branch

2024-10-02 15:49 UTC, saiarcot895 approved these changes

2024-10-14 18:28 UTC, merged